Action Triggers
---------------

Action triggers enable Evergreen to perform actions and send notifications based 
on the information in the templates.

.Action Triggers are used for
* Some Print functions
* xref:_auto_to_lost_triggers[Automatically setting overdue items to Lost]
* https://docs.libraries.coop/sitka/_patron_notifications.html[Patron Email 
Notifications]

Some templates are set at the Sitka level and cannot be customized. Most templates are customizable per library.

.Can't customize
* Print Call number
* Print PO

.Can customize
* Courtesy Notifications
* Overdue Notifications
* Lost Notifications
* Circulation Notifications
* Hold Notifications
* Patron Account Notifications


Editing Action Trigger Templates
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.Edit existing templates
. Go to *Administration -> Local Administration -> Notification/Action Triggers.*
. Filter to find the template that needs to be updated.
. Select the template and click *Actions -> Edit Selected.*
. Modify the template as needed.	
. Click *Save.*


Update Action Trigger Templates to HTML
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.If the following code is included, notices will be sent as HTML:
* Content-Type: text/html; charset="utf-8"

.This is as oppossed to the default (non-HTML) code:
* Content-Type: text/plain; charset="utf-8"

Note that all template wording must be updated to HTML, otherwise the text will not present correctly.

For example, line breaks need to be coded in (i.e. &lt;br /&gt;), otherwise the text will be all stuck together on the same line.

Another issue is that hyperlinks will no longer automatically link unless they are updated with HTML, &lt;a href=&quot;URL&quot;&gt;linked text&lt;/a&gt;

Additionally, https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references[numeric character references] must be used for some characters, e.g. if you want &lt; in the final notification, you must write &amp;lt&semi; in the template.

Here also is a reference of https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements#text_content[HTML text content elements].

.Tags known to work in action triggers include:
* &lt;a href&gt; (hyperlink)
* &lt;b&gt; (bold)
* &lt;i&gt; (italicize)
* &lt;ul&gt; and &lt;li&gt; (unordered list)
* &lt;ol&gt; and &lt;li&gt; (ordered list)
* &lt;img&gt; (embedded image)
* &lt;div&gt; (container for content) 

A div tag may be used to enclose the entire content of message.

[NOTE]
======

Here is an example of a div tag enclosing the message content of an email notification formatted in HTML:

&lt;div&gt;&ast;&ast;&ast;This is an automated message.  Please do not reply to this email.&ast;&ast;&ast;&lt;br /&gt;&lt;br /&gt;

Dear &lsqb;% user.pref_first_given_name || user.first_given_name %&rsqb; &lsqb;% user.pref_family_name || user.family_name %&rsqb;,&lt;br /&gt;&lt;br /&gt;

Our records indicate your library account is due to expire in 30 days. Please visit, call or email your local library at your convenience to renew your account in order to avoid a disruption in access to library service. &lt;br /&gt;&lt;br /&gt;

To update your account we will need to verify your address, phone number and email.  Please include this information if you're emailing us to renew your account.&lt;br /&gt;&lt;br /&gt;

Sincerely,&lt;br /&gt;
&lsqb;% lib.name %&rsqb;&lt;br /&gt;&lt;br /&gt;

.Contact your library for more information:&lt;br /&gt;&lt;br /&gt;
&lsqb;% lib.name %&rsqb;&lt;br /&gt;
&lsqb;%- SET addr = lib.mailing_address -%&rsqb;&lt;br /&gt; 
&lsqb;%- IF !addr -%&rsqb; &lsqb;%- SET addr = lib.billing_address -%&rsqb; &lsqb;%- END %&rsqb;&lt;br /&gt;
&lsqb;% addr.street1 %&rsqb; &lsqb;% addr.street2 %&rsqb;&lt;br /&gt;
&lsqb;% addr.city %&rsqb;, &lsqb;% addr.state %&rsqb;&lt;br /&gt;
&lsqb;% addr.post_code %&rsqb;&lt;br /&gt;
&lsqb;% lib.phone %&rsqb;&lt;br /&gt;
&lsqb;% lib.email %&rsqb;&lt;br /&gt;&lt;br /&gt;

If you no longer wish to receive these email notifications, you may login to your library account and change your preferences or contact your library for assistance.&lt;br /&gt;&lt;/div&gt;
======


Cloning Action Trigger Templates
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.Clone existing templates
. Go to *Administration -> Local Administration -> Notification/Action Triggers.*
. Filter to find an existing template to copy
. Select the template and click *Actions -> Clone Selected.*
. An alert will appear *Clone event definition environment as well?* -> Click *Confirm*
. Enter *Owning Library.*
. Add the library short code to the *Name* field.
. Modify the template as needed.
. Click *Save*

Naming Action Trigger Templates
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Action triggers should follow the below naming patterns. This ensures that 
old triggered events and output can be correctly identified by event_def name 
to be deleted.

[options="header"]
|===
|Notice Type | Name Pattern
|pre-due |XXX 3 Day Courtesy Notice
|overdue |XXX n Day Overdue Notice 
|overdue mark lost |XXX m Day Overdue Mark Lost 
|hold email |XXX Hold Ready for Pickup Email Notification 
|checkout receipt email |XXX Checkout Email Receipt
|hold cancelled by staff |XXX Holds Cancelled by Staff Email Notice
|shelf expired hold cancelled |XXX Shelf Expired Holds Cancelled Email Notice
|===

_XXX is a library's shortname, n & m are integers_

More information can be found on the https://bclc.wiki.libraries.coop/doku.php?id=sitka:support:administration:name_trigger[wiki name_trigger page]

Other info
~~~~~~~~~~

Events that use opt_in_setting:  'circ.default_overdue_notices_enabled'

* New/expiring accounts
* Predue/overdue/marked lost
* New due date by emergency closing
* Fine limit exceeded.

They use the following hooks:

* 'autorenewal',
* 'checkout.due',
* 'checkout.due.emergency_closing',
* 'lost',
* 'lost.auto',
* 'lost.found',
* 'penalty.PATRON_EXCEEDS_FINES'
* au.created,
* au.expired

NOTE: Emailing checkout receipt uses opt_in_setting: 'circ.send_email_checkout_receipts'

NOTE: Events related to holds (including expiring holdshelf), booking reservation,
checkin with missing pieces, recall *do not* use the opt_in_setting.

NOTE: Depending on the trigger, the Processing Delay will be calculated differently. For example, triggers acting on an item due date count from 23:59 on the date something is due, while user account expiry counts from 00:00 on the date of account expiry.

Headers and Macros
^^^^^^^^^^^^^^^^^^

If the template contains macros [% xxxxx -%] you must make sure to include the qualifiying information before the macros

Example: macro = [% real_short %]

[source,html]
----
[%- real_short = lib.shortname -%]
[%- IF (lib.ou_type == 5 || lib.ou_type == 6 || lib.ou_type == 7 || lib.ou_type == 8) && lib.shortname != 'VOMB' && lib.shortname != 'BSE' && lib.shortname != 'BGI' -%]
[%- real_short = lib.parent_ou.shortname -%]
[%- END -%]
----
 
You can log into your account here:
https://[% real_short %].[% lib.mailing_address.state %].catalogue.libraries.coop/eg/opac/login?notice=P3D

Auto to Lost Triggers
~~~~~~~~~~~~~~~~~~~~~

The auto to lost trigger and associated email notification must be set up in a very specific way.

Setting Up the Email Notification
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

. Go to *Administration -> Local Administration -> Notification/Action Triggers.*
. Filter to find an existing template to copy
. Select the template and click *Actions -> Clone Selected.*
. An alert will appear *Clone event definition environment as well?* -> Click *Confirm*
. Enter *Owning Library.*
. Add the library short code to the *Name* field.
. Set Enabled to be un-checked.
. Modify the template as needed, make sure the days overdue is correct for what the library wants.
. Click *Save*


Setting Up the Auto to Lost Trigger
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

. Go to *Administration -> Local Administration -> Notification/Action Triggers.*
. Click *New Event Definition*.
. Enter the following information:
.. Owning Library: LIBRARYCODE
.. Name: LIBRARYCODE XX Day Overdue Mark Lost
.. Hook: checkout.due
.. Enabled: leave un-checked
.. Processing Delay: XX days
.. Processing Delay Context Field: due_date
.. Reactor: MarkItemLost
.. Validator: CircIsOverdue
.. Granularity: daily
.. Max Event Validity Delay: You MUST leave this field blank
.. Retention Interval: you MUST leave this field blank
.. Context Bib Path: target_copy.call_number.record
.. Context Item Path: target_copy
.. Context Library Path: circ_lib
.. Context User Path: usr
. Click *Save*.
. Find the newly created A/T -> Edit Event Definition
. Choose Edit Paramaters tab -> Click *New Parameter*
.. Parameter Name : editor
.. Parameter Value : 0
. Click *Save*.


Turning on Auto to Lost
^^^^^^^^^^^^^^^^^^^^^^^

When auto to lost is turned on for the very first time it will run overnight and set everything that is past the overdue threshold 
to lost. This is contingent on there being no value set for _Max Event Validity Delay_ or _Retention Interval_; if values are
present not all long overdue items will be set to lost.

. Confirm that everything is correct for both the email notification and the auto to lost trigger.
. Check the box for Enabled in the email notification.
. Click *Save*.
. Check the box for Enabled in the auto to lost.
. Click *Save*.
. The next day, open the auto to lost trigger.
. Enter the following information:
.. Max Event Validity Delay: Enter a value between the Processing Delay and Processing Delay + Retention 
Interval
.. Retention Interval: 3 mons
. Click *Save*.

[CAUTION]
=========
There is a bug preventing values from being removed from the _Max Event Validity Delay_ or _Retention Interval_ fields in the
staff client.  This means that inactive auto to lost triggers can't just be turned back on in the staff client; they should
be referred to Tier2 Support.
=========

Editing the Auto to Lost Trigger
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

