Cataloguing Issues
------------------

Sitka’s Cataloguing Policy defines the standards and best practices for cataloguing within the shared Sitka catalogue to ensure that all libraries are treating bibliographic records in the same manner when they are editing, creating, or adding records.

https://docs.libraries.coop/policy/_cataloguing_policy.html

All staff that perform cataloguing tasks at Sitka libraries are expected to familiarize themselves with this policy and commit to uphold it as they work with records in the Sitka catalogue.

The goal is to have a database of high quality bibliographic records that are shared by all libraries. Ideally there is one MARC record in the database for each discrete bibliographic title which all libraries add their holdings to. All Sitka libraries must follow the same policies when editing MARC records to ensure that records accurately describe the items that are attached to them.

[NOTE]
======
There is a known bug (https://bugs.launchpad.net/evergreen/+bug/1982892[LP 1982892]) where in the Record Notes tab in a bibliographic record, the value of the Creator and Editor columns is always "1" or the username of the account that has an id of "1". This means the information about the Creator or Editor of a Bib Record Note is currently incorrect and cannot be used as a reference.
======

Bad Cataloguing
~~~~~~~~~~~~~~~

If we are notified of bad cataloguing, we must follow up with the offending library about their cataloguer. 

. Ask Tina for the audit log 
. Run SQL to find home library of the offending user - Jennifer/Christine
. Save a copy of the improperly modified MARC (can be copied from Flat Text Editor in bib record) 
. Review one of the non-production servers for the original record
. Manually update the changed record to match the original record
. Create a new ticket to notify the offending library
.. link to original ticket (Refers to)
.. in the message to the library, include links to cataloguing policy
.. provide details about how the cataloguing policy was violated
.. share the problematic MARC
.. explain why this specific example was a problem
.. indicate we've made updates

By saving a reference of the problematic MARC, it is a record of the problematic changes, as well as any changes which may have been made in between the time the bad edits were made and the snapshot was taken on the non-prod server (i.e. there may have been other non-problematic updates by others in that time). While sharing the problematic MARC with the library whose staff made the bad updates can help the library (so they know what not to do, as well as having a reference of any other non-problematic info that may have been added), it is also a reference for us. (If it is a situation where many records were edited this may not be feasible, but for single record issues this is not unweildy.) If we choose not to share the old problematic MARC with the library, it can also be added as a comment to a ticket for our reference.

[TIP]
======
_Here is suggested wording for following up with the library whose staff made the bad changes:_

Hello,

It has been brought to our attention that staff at your library improperly modified a bibliogaphic record. On *(date)*, account *(user)* *(edited in problematic way)* bibliographic record *(db ID #, link to bib record)*.

Sitka’s Evergreen Policy states "All staff performing cataloguing functions in Sitka’s Evergreen are expected to follow the same cataloguing standards when working with records."
https://docs.libraries.coop/policy/_cataloguing_standards.html

"Cataloguers should be cautious when editing existing bibliographic records in the Sitka catalogue. Changes to a bibliographic record affect ALL libraries with holdings attached. In our consortium, with over 100 libraries, a single change can have a significant effect."
https://docs.libraries.coop/policy/_editing_bibliographic_records.html

Cataloguers are encouraged to correct obvious typos or otherwise enhance records, but should refrain from making changes that result in incorrect coding of a record.

This was the MARC of the problematically updated record:

*(Flat Text MARC with bad cataloguing)*

The *(outline of problem and why issue)*. To resolve these problematic changes, we have have reverted the bibliographic record to an earlier version.

Please let us know if you have questions about this or if there are any related issues.
======

Bad Record Merge
~~~~~~~~~~~~~~~~

If we are notified of a bad record merge

. Check the lead record Record Notes tab to get the ID of records merged
. Ask Tina for audit log to determine what user merged the records
. Create a new ticket to notify the offending library
.. link to original ticket (Refers to)
.. in the message to the library, include a link to cataloguing policy
.. provide details about how the cataloguing policy was violated
.. provide specific examples
. Undelete the merged records
. Create separate tickets to notify any affected libraries that they will need to transfer their holdings back to the original record 
.. link to original ticket (Refers to)
.. in message to libraries, include link to instructions for transfering holdings

[TIP]
======
_Here is suggested wording for following up with the library whose staff merged the records improperly:_

Hello,

It has been brought to our attention that staff at your library improperly merged bibliogaphic records.

On *(date)*, account *(user)* merged bibliographic record *(db ID)* into the following other records:

* (db ID)
* (db ID)
* (db ID)

We have restored these records (so you do not have to update them now), but we are reaching out to prevent something like this from happening in the future as multiple libraries' holdings were impacted by these actions.

Sitka's Evergreen Policy states "All staff performing cataloguing functions in Sitka’s Evergreen are expected to follow the same cataloguing standards when working with records."
https://docs.libraries.coop/policy/_cataloguing_standards.html

"Changes to a bibliographic record affect ALL libraries with holdings attached. In our consortium, with over 100 libraries, a single change can have a significant effect."
https://docs.libraries.coop/policy/_editing_bibliographic_records.html

Before merging records, cataloguers must ensure the records are a match: https://docs.libraries.coop/policy/_the_cataloguing_workflow.html#_is_it_a_match

Please let us know if you have questions about this or if there are any related issues.
======

[TIP]
======
_Here is suggested wording for following up with a library whose holdings were affected by the merged records:_

Hello,

It has been brought to our attention that staff at another library improperly merged bibliogaphic records.

.On *(date)*, bibliographic record *(db ID)* was merged into the following other records:

* (db ID)
* (db ID)
* (db ID)

We have restored the original records, but we are reaching out as you should review and transfer your holdings as needed.

Instructions for transferring holdings can be found here: https://docs.libraries.coop/sitka/_transferring_holdings.html

If the affected items all have the same call number, they may need to be transferred individually as items (rather than holdings): https://docs.libraries.coop/sitka/_transferring_holdings.html#_transfer_item

Please let us know if you have questions about this or if there are any related issues.
======
