Cataloguing Issues
------------------

Sitka’s Cataloguing Policy defines the standards and best practices for cataloguing within the shared Sitka catalogue to ensure that all libraries are treating bibliographic records in the same manner when they are editing, creating, or adding records.

All staff that perform cataloguing tasks at Sitka libraries are expected to familiarize themselves with this policy and commit to uphold it as they work with records in the Sitka catalogue.

The goal is to have a database of high quality bibliographic records that are shared by all libraries. Ideally there is one MARC record in the database for each discrete bibliographic title which all libraries add their holdings to. All Sitka libraries must follow the same policies when editing MARC records to ensure that records accurately describe the items that are attached to them.

https://docs.libraries.coop/policy/_cataloguing_policy.html


If we are notified of bad cataloguing we must follow up with the offending library/cataloguer. 

. Ask Tina for audit log 
. Run SQL to find home library of the offending user - Jennifer/Christine
. Create a new ticket to notify the offending library
.. add refers to link to the original ticket
.. include a link to cataloguing policy
.. provide details about how the cataloguing policy was violated
.. provide examples
. Check one of the non-production servers for the original record
. Manually update the changed record to match the original record

If we are notified of a bad record merge

. Check the lead record Record Notes tab to get the ID of records merged and the username of the person who did it.
. Run SQL to find home library of the offending user - Jennifer/Christine
. Create a new ticket to notify the offending library
.. add refers to link to the original ticket
.. include a link to cataloguing policy
.. provide details about how the cataloguing policy was violated
.. provide examples
. Undelete the merged records
. Create separate tickets to notify any affected libraries that they will need to transfer their holdings back to the original record 