Organizational Units
--------------------

Changing an Organization's Name
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

. Go to Server Administration -> Organizational Units.
. Find the org unit in the tree.
. Update the value in the _Name_.
. Click *Save*.
. Ask a tech to restart applicable services during a maintenance window.

[CAUTION]
=========
Changing the name of an organizational unit may affect 3rd party services.

If a library uses any of the following 3rd party services, those services will need to be notified
of the name change:

* Biblicommons
* Overdrive
* ULS / Other Acquisitions vendors

=========


Changing an Organization's Structure
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

https://bc.libraries.coop/ufaqs/what-do-i-need-to-do-to-add-a-new-branch-bookmobile-or-book-locker-for-my-library/[FAQ - What
do I need to do to add a new branch, bookmobile, or book locker for my library?]

Adding a branch, bookmobile, book locker, or other additional organizations unit to a library or system changes 
the organizations structure. This involves a significant amount of work, especially when changing a standalone library
into a system with multiple org units attached.

When a library submits a ticket tha involves adding an org unit:

. Respond to the library and let them know there is a cost involved and a quote will be provided.
. Alert Sharon to the library's request and the need for a quote.
. Once the library has confirmed they wish to go ahead with the change, confirm the names that will be used for the
the new and existing org units and the date on which the new structure should go live.
.. We require 4 weeks notice for a new branch or bookmobile. 
.. For book lockers and other 3rd party products libraries should anticipate a 3 to 6 month turnaround to assess the 
product and whether or not it compatible with Evergreen as per our 
https://docs.libraries.coop/policy/_3rd_party_service_integration.html[3rd Party Service Integration policy].
. Once we have the needed information assign the ticket to Tina. 
https://wiki.libraries.coop/sitka/support/ad_hoc_request/orgunit[Information on the changes needed to Evergreen] 
can be found on the wiki.

Public Catalogue Search Scope
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

When a standalone library becomes a multi-branch library the search scope for their public catalogue will need
to be updated to use the system org unit ID if the original library org unit has become a branch.

The search scope for the LibPress search box will also need to be updated to match.


[CAUTION]
=========

Changing the structure of an organizational unit may affect 3rd party services.

If a library uses any of the following 3rd party services, those services will need to be notified of any changes to 
the org unit names.

* Biblicommons (also need the org unit IDs)
* Overdrive
* ULS / Other Acquisitions vendors

=========
